version: "3"
services:
  unrealircd:
    build:
      context: unrealircd
      args:
        - hostuid=1000
    networks:
      default:
        aliases:
          - ircd
    ports:
      - "6667:6667"
      - "6697:6697"
    volumes:
      - "./config/unrealircd:/home/irc/unrealircd/conf"
      - "./data/unrealircd:/home/irc/unrealircd/data"
      - "./logs/unrealircd:/home/irc/unrealircd/logs"

  anope:
    build:
      context: anope
      args:
        - hostuid=1000
    depends_on:
      - unrealircd
    networks:
      default:
        aliases:
          - services
    ports:
      - "7226:7226"
    volumes:
      - "./config/anope:/home/irc/services/conf"
      - "./data/anope:/home/irc/services/data"
      - "./logs/anope:/home/irc/services/logs"

  pylink:
    build:
      context: pylink
      args:
        - hostuid=1000
    depends_on:
      - unrealircd
    networks:
      default:
        aliases:
          - pylink
    volumes:
      - "./config/pylink:/home/irc/conf"
      - "./data/pylink:/home/irc/data"
      - "./logs/pylink:/home/irc/log"
